# ============================================================
# ARGOS WireGuard — Phone1 (полный тоннель через AU)
# Весь интернет-трафик идёт через AU (Australia East)
# WG IP: 10.200.0.10  |  Gateway: 20.53.240.36:51820
# ============================================================

[Interface]
PrivateKey = uE5U6c+fR1qZsweFbCl7SMsQSM4RGTdM+cNYXQMEOmM=
Address = 10.200.0.10/24
DNS = 1.1.1.1, 8.8.8.8

# AU — gateway (Australia East)
[Peer]
PublicKey = 0XlzOCK3hX7KigbcvHtre5KZdY5NPtPW8w43OEqi3HU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 20.53.240.36:51820
PersistentKeepalive = 25
