# ============================================================
# ARGOS WireGuard — Phone1 (полный тоннель через JP1)
# Весь интернет-трафик идёт через JP1 (Japan East)
# WG IP: 10.200.0.10  |  Gateway: 40.81.208.101:51821
# ============================================================

[Interface]
PrivateKey = uE5U6c+fR1qZsweFbCl7SMsQSM4RGTdM+cNYXQMEOmM=
Address = 10.200.0.10/24
DNS = 1.1.1.1, 8.8.8.8

# JP1 — gateway (Japan East)
[Peer]
PublicKey = i3nHuoWUAYqjBFnclp8ZqcEaEtXf8aI93xPPFw7rbXg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 40.81.208.101:51821
PersistentKeepalive = 25
