# ============================================================
# ARGOS WireGuard — Tablet (полный тоннель через JP2)
# WG IP: 10.200.0.12  |  Gateway: 172.207.209.134:51820
# ============================================================

[Interface]
PrivateKey = GCO6bVaW8RnhqUCoIzrQMjJThFau6+JiBf3d0S7mnlw=
Address = 10.200.0.12/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = y4X9oNGUk18MWjmvaK4Z0JhCY2+yDpIM9TMVz/Ontyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 172.207.209.134:51820
PersistentKeepalive = 25
