# ============================================================
# ARGOS WireGuard — Tablet (полный тоннель через AU)
# WG IP: 10.200.0.12  |  Gateway: 20.53.240.36:51820
# ============================================================

[Interface]
PrivateKey = GCO6bVaW8RnhqUCoIzrQMjJThFau6+JiBf3d0S7mnlw=
Address = 10.200.0.12/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = 0XlzOCK3hX7KigbcvHtre5KZdY5NPtPW8w43OEqi3HU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 20.53.240.36:51820
PersistentKeepalive = 25
