#!/usr/bin/env python3
"""build_argos_report.py

Run health_check.py and the consciousness module tests, then write a combined
Markdown report to reports/argos_ci_report.md.

Exit codes:
  0  – both commands succeeded
  1  – health_check.py failed (always fatal)
  2  – pytest failed (tests failed)
  3  – both failed
"""
from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
REPORT_DIR = REPO_ROOT / "reports"
REPORT_FILE = REPORT_DIR / "argos_ci_report.md"

TEST_FILE = REPO_ROOT / "tests" / "test_consciousness_module.py"


def _run(cmd: list[str], *, cwd: Path) -> tuple[int, str]:
    """Run *cmd* and return (exit_code, combined_output)."""
    result = subprocess.run(
        cmd,
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return result.returncode, result.stdout


def _status(code: int) -> str:
    return "✅ PASS" if code == 0 else f"❌ FAIL (exit {code})"


def main() -> int:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    print("=== ARGOS Report Builder ===")
    print(f"Timestamp : {now}")
    print(f"Repo root : {REPO_ROOT}")

    # ── (B) health_check.py ───────────────────────────────────────────────
    print("\n[B] Running health_check.py …")
    hc_cmd = [sys.executable, "health_check.py"]
    hc_code, hc_out = _run(hc_cmd, cwd=REPO_ROOT)
    print(hc_out)
    print(f"health_check exit code: {hc_code}")

    # ── (C) pytest ────────────────────────────────────────────────────────
    if TEST_FILE.exists():
        pt_cmd = [sys.executable, "-m", "pytest", str(TEST_FILE), "-v"]
        print(f"\n[C] Running pytest {TEST_FILE.name} …")
    else:
        pt_cmd = [sys.executable, "-m", "pytest", "tests", "-q"]
        print("\n[C] test_consciousness_module.py not found – falling back to: pytest tests -q")

    pt_code, pt_out = _run(pt_cmd, cwd=REPO_ROOT)
    print(pt_out)
    print(f"pytest exit code: {pt_code}")

    # ── Write Markdown report ─────────────────────────────────────────────
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    report = f"""# 🧠 ARGOS CI Report

**Generated:** {now}

---

## (B) Health Check — `python health_check.py`

**Status:** {_status(hc_code)}

<details><summary>Output</summary>

```
{hc_out.strip()}
```

</details>

---

## (C) Pytest — consciousness module

**Command:** `{" ".join(pt_cmd)}`  
**Status:** {_status(pt_code)}

<details><summary>Output</summary>

```
{pt_out.strip()}
```

</details>

---

*Report generated by `.github/scripts/build_argos_report.py`*
"""

    REPORT_FILE.write_text(report, encoding="utf-8")
    print(f"\nReport written to: {REPORT_FILE}")

    # ── Determine overall exit code ───────────────────────────────────────
    overall = 0
    if hc_code != 0:
        print("ERROR: health_check.py failed – marking workflow as failed.")
        overall |= 1
    if pt_code != 0:
        print("ERROR: pytest failed – marking workflow as failed.")
        overall |= 2

    return overall


if __name__ == "__main__":
    sys.exit(main())
